### ISSUE TITLE
Problem with setup instructions

### ISSUE THREAD

**Issue by ghost** [raspitv/raspio_duino#1]
As per set-up instructions I the the following:
pi@bgPi3 /tmp $ wget http://project-downloads.drogon.net/gertboard/avrdude_5.10-4_armhf.deb

But I get:
--2015-05-31 15:43:06--  http://project-downloads.drogon.net/gertboard/avrdude_5.10-4_armhf.deb
Resolving project-downloads.drogon.net (project-downloads.drogon.net)... 195.10.226.169, 2a00:ce0:2:feed:beef:cafe:0:4
Connecting to project-downloads.drogon.net (project-downloads.drogon.net)|195.10.226.169|:80... failed: No route to host.
Connecting to project-downloads.drogon.net (project-downloads.drogon.net)|2a00:ce0:2:feed:beef:cafe:0:4|:80... failed: Address family not supported by protocol.
pi@bgPi3 /tmp $ 

Please can you advise me on what to do, thanks

**Comment by raspitv** [comment]
Do you have internet access on that Pi? Can you access other sites?

I just downloaded  http://project-downloads.drogon.net/gertboard/avrdude_5.10-4_armhf.deb and the URL is working fine. It must be either a temporary outage issue or an issue with your Pi's internet connection.

**Comment by ghost** [comment]
Hi Alex,
Thanks for the reply.  I put the Dunino on an old A+ RPi with a USB to Ethernet connector and connected to it via SSH from my iMac.  I thought all was working OK, but I guess something must be wrong.  I don't know enough about the command line stuff to check if the pi is connected to the internet   I’ll get my RPi2 that has a proper ethernet port out of its case so I can plug in the Duino to that instead and start again.

Very good instructions on the soldering by the way which task I have just completed.  I did spend a bit of time trawling your RPi TV site wondering how to contact you with no obvious way.  I googled your name an came across your twitter account.  I’ve only used twitter once before several years ago and found I could only put in a few characters per tweet, so apologies for a small collection of garbled tweets.  I then came across the link to github so managed to contacted put in my issue on there.   If you have managed use the URL then the fault is undoubtedly at my end, and your note is greatly appreciated.  

Kind Regards
Bernard

On 18 Nov 2015, at 22:18, Alex Eames notifications@github.com wrote:

Do you have internet access on that Pi? Can you access other sites?

I just downloaded http://project-downloads.drogon.net/gertboard/avrdude_5.10-4_armhf.deb http://project-downloads.drogon.net/gertboard/avrdude_5.10-4_armhf.deb and the URL is working fine. It must be either a temporary outage issue or an issue with your Pi's internet connection.
